apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  annotations:
    appName: "activemq-5.10.0"
spec:
  replicas: 2
  serviceName: activemq
  selector:
    matchLabels:
      io.kubernetes/app-name: activemq
      io.activemq/version: "5.10"
  template:
    metadata:
      labels:
        io.kubernetes/app-name: activemq
        io.activemq/version: "5.10"
    spec:
      imagePullSecrets:
        - name: 
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  io.kubernetes/app-name: activemq
                  io.activemq/version: "5.10"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: anythin
                    operator: "In"
                    values:
                      - "abc"
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: activemq-data
      containers:
        - name: activemq
          imagePullPolicy: Always
          image: dipayanp007/amq:5.10-beta
          env:
          - name: ACTIVEMQ_BROKER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: activemq-config
            - secretRef:
                name: activemq-broker-secrets
            - secretRef:
                name: activemq-ui-secrets
          # - name: ACTIVEMQ_DATA_DIR
          #   value: "/opt/activemq/data" 
          # - name: ACTIVEMQ_DATA_DIR_SIZE
          #   value: "100" 
          # - name: ACTIVEMQ_DATA_TMP_SIZE
          #   value: "50" 
          # - name: ACTIVEMQ_OPENWIRE_PORT
          #   value: "61616" 
          # - name: ACTIVEMQ_AMQP_PORT
          #   value: "5672" 
          # - name: ACTIVEMQ_STOMP_PORT
          #   value: "61613" 
          # - name: ACTIVEMQ_MQTT_PORT
          #   value: "1883" 
          # - name: ACTIVEMQ_WS_PORT
          #   value: "61614"
          # - name: PROTECTED_BROKER
          #   value: "false"
          # - name: ACTIVEMQ_USERNAME
          #   value: "admin"
          # - name: ACTIVEMQ_PASSWORD
          #   value: "admin"
          # - name: ACTIVEMQ_WEBADMIN_USERNAME
          #   value: "admin"
          # - name: ACTIVEMQ_WEBADMIN_PASSWORD
          #   value: "admin123"
          # args:
          #   - "bash"
          #   - "-c"
          #   - "sleep 10000"
          ports:
          - name: ui
            containerPort: 8161
          - name: openwire
            containerPort: 61616
          - name: amqp
            containerPort: 5672
          - name: stomp
            containerPort: 61613
          - name: mqtt
            containerPort: 1883
          - name: ws
            containerPort: 61614
          volumeMounts:
            - mountPath: /opt/activemq/data/kahadb
              name: data